services:
  - type: web
    name: jina-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"

  - type: static
    name: jina-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
